// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbc8-J1UQY7OGy3rpcVL7ncUSiaA7sdX4',
    appId: '1:152421436128:web:e085f808ec6619fa6c1e85',
    messagingSenderId: '152421436128',
    projectId: 'rent-cf27c',
    authDomain: 'rent-cf27c.firebaseapp.com',
    storageBucket: 'rent-cf27c.appspot.com',
    measurementId: 'G-503NKSPGQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2QsxQwfbRPtgxO_VLnKOYF-v_tHz5360',
    appId: '1:152421436128:android:7e1bc2af37c2430c6c1e85',
    messagingSenderId: '152421436128',
    projectId: 'rent-cf27c',
    storageBucket: 'rent-cf27c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuu9ZwM_Tjj2SXVuDirGtfMM-cesHBRzk',
    appId: '1:152421436128:ios:e7c1a3aae202f5156c1e85',
    messagingSenderId: '152421436128',
    projectId: 'rent-cf27c',
    storageBucket: 'rent-cf27c.appspot.com',
    iosBundleId: 'com.example.rent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuu9ZwM_Tjj2SXVuDirGtfMM-cesHBRzk',
    appId: '1:152421436128:ios:e7c1a3aae202f5156c1e85',
    messagingSenderId: '152421436128',
    projectId: 'rent-cf27c',
    storageBucket: 'rent-cf27c.appspot.com',
    iosBundleId: 'com.example.rent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbc8-J1UQY7OGy3rpcVL7ncUSiaA7sdX4',
    appId: '1:152421436128:web:e195c57c2bfe2c446c1e85',
    messagingSenderId: '152421436128',
    projectId: 'rent-cf27c',
    authDomain: 'rent-cf27c.firebaseapp.com',
    storageBucket: 'rent-cf27c.appspot.com',
    measurementId: 'G-QF9CJBTT9F',
  );
}
